app:
    restart: "always"
    build: .
    ports:
        - "5000:5000"
    command: "gunicorn -w2 wsgi:app -b 0.0.0.0:5000 --log-level warning --error-logfile=-"
    volumes:
        - ".:/app"
    links:
        - redis

celery:
    restart: "always"
    build: .
    command: "src/run_celery.sh"
    volumes:
        - ".:/app"
    links:
        - redis

redis:
    restart: "always"
    image: "redis"
